### ISSUE TITLE
Decide what subdomain you want

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/fmLTPBR_design#6]
When you know what you want your `****.riverscapes.xyz subdomain` to be (e.g. `fmltpbr.riverscapes.xyz`) or something hopefully more memorable, fill out a request [here](https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/subdomain.html)

**Comment by nick4rivers** [comment]
@joewheaton and @philipbaileynar  I sent a request the other day. It's as above gmltpbr.riverscapes.xyz. Can you hook it up?

**Comment by philipbaileynar** [comment]
@MattReimer can you hookup this riverscapes subdomain to the docs in this repo please. Thanks

**Comment by MattReimer** [comment]
It's hooked up. Make sure to do a pull on the repo since there is a new CNAME file and `_config.yml` has changed. 

Also give it a few hours for the CNAME record to resolve.

**Comment by nick4rivers** [comment]
Nice all, thanks a ton.

**Comment by nick4rivers** [comment]
Matt,

You changed it to http://gmltpbr.riverscapes.xyz/ <http://gmltpbr.riverscapes.xyz/> i.e., gmLTPBR instead of fmLRPBR.

I already changed the url in the .yml and pushed it back to git, but you may need to do something on your end?

Thanks again, sorry for the confusion

Nick w.

**Comment by joewheaton** [comment]
I hate to be the pain in the ass, but did you really mean
gmltpbr.riverscapes.xyz (what M@ did and you asked) or should it be
fmltpbr.riverscapes.xyz?
_____________________
Dr. Joseph M. Wheaton
435-554-1247 (direct) | http://www.joewheaton.org

**Comment by nick4rivers** [comment]
Yes @MattReimer and @joewheaton , fmltpbr.

Sorry all for the confsion

**Comment by MattReimer** [comment]
Ok. Corrected in the DNS Records. As usual, your mileage may vary depending on how far you are from the server. Give it an hour or two to propagate
