### ISSUE TITLE
Double check site contents

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/fmLTPBR_design#7]
@philipbaileynar  could you just have a look at this site and make sure I'm not doing anything too out of practice moving forward. Thanks!!

**Comment by philipbaileynar** [comment]
Yep, looks like a good start. You can delete the styleguide file. That's just to show you how to style content.

I say go for it and start writing markdown file content!

**Comment by nick4rivers** [comment]
@philipbaileynar  and/or @MattReimer  Could you quickly tell me how to add an image to the banner/header? I've done it a couple times and it seems like my changes to the _site/index.html don't stick?

**Comment by MattReimer** [comment]
Hey Nick,

In your docs folder put in a `png` file with the following path:

```
docs/assets/images/HeaderBackground.png
```

That should do it.

**Comment by MattReimer** [comment]
Also I should mention that `_site` is what jekyll builds every time. it is ephemeral and constantly beign rebuilt and you should never change anything there.

**Comment by nick4rivers** [comment]
That makes sense...How then do I put an image on the banner .- similar to the BRAT page?

![Screen Shot 2020-04-13 at 1 01 11 PM](https://user-images.githubusercontent.com/34071692/79156000-ecca6c00-7d86-11ea-83a3-b37c94ee2856.png)

**Comment by MattReimer** [comment]
For that you need some template magic

Take a look here
<https://github.com/Riverscapes/pyBRAT/blob/master/docs/_includes/header.html>

create a file:`docs/_includes/header.html` 

and drop whatever html snippet you need in there.

the code statements:

```
{% if page.url == "/" %}
```

Are called liquid tags and they let you assert some basic if/else logic on jekyll (but not much so keep expectations low)

**Comment by nick4rivers** [comment]
Very cool @MattReimer thanks!!
